services:
  kong-database: # PostgreSQL cho Kong metadata
    image: postgres:13
    container_name: kong_database
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck: # Kiểm tra DB ready trước khi start Kong. Kong cần database để lưu cấu hình (services, routes, plugins).
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      timeout: 3s
      retries: 5

  kong-migration: # Chạy migration cho Kong DB
    image: kong:3.4.2
    container_name: kong_migration
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
    depends_on:
      kong-database:
        condition: service_healthy # Chờ DB healthy

  kong: # Gateway Kong chính
    image: kong:3.4.2
    container_name: kong_gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000" # Gateway
      - "8001:8001" # Admin
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kong health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  kong_data:
